points:
  zones:
    matrix:
      columns:
        outer:
          key:
            column_net: P020
        pinky:
          key.stagger: 0
          key:
            column_net: P022
        ring:
          key.stagger: 5
          key.column_net: P024
        middle:
          key.stagger: 0
          key.column_net: P100
        index:
          key.stagger: 0
          key.column_net: P011
        inner:
          key.stagger: 0
          key.column_net: P017
      rows:
        mod:
          row_net: P113
        bottom:
          row_net: P115
        home:
          row_net: P002
        top:
          row_net: P029
    thumbA:
      key.spread: 25
      row_net: P115
      anchor:
        ref: matrix_inner_bottom
        rotate: 75
        shift: [17, -30]
      columns:
        near: 
          key.column_net: P009
        home: 
          key.column_net: P010
    thumbB:
      key.spread: 25
      row_net: P002
      anchor:
        ref: matrix_inner_bottom
        rotate: 75
        shift: [37, -35]
      columns:
        far:
          key.column_net: P009
        mod:
          key.column_net: P010
outline:
  left:
    - where: true
      what: rectangle
      size: [cx + 2, cy + 2]
      fillet: 2
pcbs:
  left:
  outlines:
    main:
      outline: left
    footprints:
      keyswitches:
        where: true
        what: choc
        params:
            hotswap: true
            from: "{{col_net}}"
            to: "{{colrow}}"
      nice_nano:
        what: nice_nano
        params: 
          orientation: up
        where:
          ref: matrix_inner_num
          shift: [-9, -2]

