units:
  # Variables for padding
  kx: cx
  ky: cy
  # Variables for spacing
  px: kx + 2
  py: ky + 2

  padding: 4
  pad: 2
  spacing: 2

  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: .005
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0
points:
  key:
    padding: cy + spacing
    spread: cx + spacing
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      columns:
        one:
          key.column_net: P020
          rows.bottom.skip: true
        two:
          key.stagger: 2
          key.column_net: P022
        three:
          key.stagger: 2
          key.column_net: P024
        four:
          key.stagger: 2
          key.column_net: P100
        five:
          key.stagger: 2
          key.column_net: P011
        six:
          key.stagger: -5
          key.column_net: P017
          rows.bottom.skip: true
      rows:
        bottom:
          row_net: P113
        home:
          row_net: P115
        top:
          row_net: P002
        num:
          row_net: P029
        mod:
          row_net: P031
    thumbs:
      key.row_net: P115
      anchor:
<<<<<<< Updated upstream
        ref: matrix_six_home
        shift: [50, -45]
      columns:
        layer:
          key.column_net: P009
          key.splay: 40
=======
        ref: matrix_six_bottom
        shift: [55, -18]
      columns:
        layer:
          key.column_net: P009
          key.splay: 65
>>>>>>> Stashed changes
          rows.home.width: 1.5kx
          rows.in.width: 1.5kx
          rows.home.shift: [-4.5, 0]
        space:
          key.column_net: P010
      rows:
        bottom:
          row_net: P009
        home:
          row_net: P010
        in:
  mirror:
    ref: matrix_six_num
    distance: 180
outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
      bound: false
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_one_mod
          shift: [-.5px, 0.5py]
        - ref: matrix_two_mod
          shift: [-0.5px, 0.5py]
        - ref: matrix_three_mod
          shift: [-0.5px, 0.5py]
        - ref: matrix_four_mod
          shift: [-0.5px, 0.5py]
        - ref: matrix_five_mod
          shift: [-0.5px + pad, 0.5py - pad]
        - ref: matrix_six_mod
          shift: [0.5px, 0.5py]
        - ref: thumbs_space_in
          shift: [1.5px, .5px]
        - ref: thumbs_space_bottom
          shift: [1px + pad, 1py]
        - ref: thumbs_layer_bottom
          shift: [0.5px, 0.5py]
        - ref: thumbs_layer_in
          shift: [-0.5px, -0.5py]
        # Bottom
        - ref: matrix_five_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_four_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_three_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_three_bottom
          shift: [0.5px - pad, -0.5py - pad]
        - ref: matrix_two_bottom
          shift: [0.5px + pad, -0.5py]
        - ref: matrix_two_bottom
          shift: [-0.5px + pad, -0.5py]
        - ref: matrix_one_home
          shift: [-0.5px, -0.5py]
        - ref: matrix_one_home
          shift: [-0.5px, 0.5py]
        - ref: matrix_one_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_one_mod
          shift: [-0.5px, -0.5py]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_one_mod
          shift: [-.5px, 0.5py]
        - ref: mirror_matrix_two_mod
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_three_mod
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_three_mod
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_four_mod
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_five_mod
          shift: [-0.5px + pad, 0.5py - pad]
        - ref: mirror_matrix_six_mod
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_six_mod
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbs_space_in
          shift: [1.5px, .5px]
        - ref: mirror_thumbs_space_bottom
          shift: [1px + pad, 1py]
        - ref: mirror_thumbs_layer_bottom
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbs_layer_in
          shift: [-0.5px, -0.5py]
        # Bottom
        - ref: mirror_matrix_five_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_five_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_four_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_three_bottom
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_three_bottom
          shift: [0.5px - pad, -0.5py - pad]
        - ref: mirror_matrix_two_bottom
          shift: [0.5px + pad, -0.5py]
        - ref: mirror_matrix_two_bottom
          shift: [-0.5px + pad, -0.5py]
        - ref: mirror_matrix_one_home
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_one_home
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_one_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_one_mod
          shift: [-0.5px, -0.5py]
  xl_board_left:
    - what: polygon
      operation: stack
      points:
        # Top
        - ref: matrix_one_mod
          shift: [-px - caseBorder, py + caseBorder]
        - ref: matrix_two_mod
          shift: [-px - caseBorder, py + caseBorder]
        - ref: matrix_three_mod
          shift: [-px - caseBorder, py + caseBorder]
        - ref: matrix_four_mod
          shift: [-px - caseBorder, py + caseBorder]
        - ref: matrix_five_mod
          shift: [-px + caseBorder, py + caseBorder]
        - ref: matrix_six_mod
          shift: [px + caseBorder, py + caseBorder]
        - ref: matrix_six_num
          shift: [px + caseBorder , py + caseBorder]
        - ref: matrix_six_home
          shift: [px + caseBorder , py + caseBorder]
        - ref: matrix_five_bottom
          shift: [2px + caseBorder, py + caseBorder]
        - ref: thumbs_space_bottom
          shift: [px + caseBorder, py + caseBorder]
        - ref: thumbs_space_bottom
          shift: [1.05px + caseBorder, .75py + caseBorder]
        - ref: thumbs_space_bottom
          shift: [1.05px + caseBorder, -1.25py + caseBorder]
        - ref: thumbs_layer_home
          shift: [-.75px + caseBorder, -2py - caseBorder]
        - ref: thumbs_layer_in
          shift: [-1px + caseBorder, -2py - caseBorder]
        # Bottom
        - ref: matrix_five_bottom
          shift: [px,-2py]
        - ref: matrix_four_bottom
          shift: [px + caseBorder, -py - caseBorder]
        - ref: matrix_three_bottom
          shift: [px + caseBorder, -py - caseBorder]
        - ref: matrix_three_bottom
          shift: [px + caseBorder, -py - caseBorder]
        - ref: matrix_two_bottom
          shift: [px + caseBorder, -py - caseBorder]
        - ref: matrix_two_bottom
          shift: [-px + caseBorder, -py - caseBorder]
        - ref: matrix_one_home
          shift: [-px - caseBorder, -py - caseBorder]
        - ref: matrix_one_top
          shift: [-px - caseBorder, -py - caseBorder]
        - ref: matrix_one_mod
          shift: [-px - caseBorder, -py - caseBorder]
  xl_board_key_cutouts:
    - name: xl_board_left
    - operation: subtract
      name: keys
pcbs:
  left:
  outlines:
    main:
      outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^(matrix_|thumbs_).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode_main:
        what: diode
        where: /^matrix_(?!(?:six_top|six_home|three_home|one_num|one_bottom|four_top|four_mod)).*|^thumbs_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -3.5]
          rotate: 90
      # Move a diode so it doesn't conflict with controller
      diode_weird1:
        what: diode
        where: matrix_six_top
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -16.0]
          rotate: 90
      # Move another diode so it doesn't conflict with controller
      diode_weird2:
        what: diode
        where: matrix_six_home
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -9.5]
          rotate: 90
      # Move some other diodes so they don't conflict with mounting holes
      diode_mounting_hole_conflict1:
        what: diode
        where: /^matrix_(?:three_home|one_num|one_bottom)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, 3.5]
          rotate: 90
      diode_mounting_hole_conflict2:
        what: diode
        where: /^matrix_(?:four_top|four_mod)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.8, -4.5]
          rotate: 90
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_six_num
          shift: [-9, -1.5]
          rotate: -180.0
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_four_home
          shift: [-7, 5.5]
          rotate: 90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_six_top
          shift: [9.0, 2.8]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: matrix_six_top
          shift: [8.8, -6.0]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: matrix_five_mod
          shift: [-px, py]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: matrix_one_bottom
          shift: [px, -py]
      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_two_num
          shift: [-px, -py]
      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_five_top
          shift: [-px, py]
      hole_center:
        what: mountinghole
        where:
          ref: matrix_four_bottom
          shift: [-px, py]
      # Write "Caldera" on the PCB
      front_text: &text
        what: text
        where: &textWhere
          ref: matrix_four_num
          shift: [-8.7, 5.5]
        params: &textParams
          text: 63L03N
          justify: left
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^(mirror_matrix_|thumb).*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          # Rotate the key switches upside-down (easier to fit controller that way)
          rotate: 180
      # Main diodes
      diode_main:
        what: diode
        where: /^(mirror_matrix_|thum)(?!(?:four_home|two_bottom|two_num|five_bottom|five_num|six_num)).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, -3.5]
          rotate: 90
      # Move a diode so it doesn't conflict with mounting hole
      diode_mounting_hole_conflict:
        what: diode
        where: /^(mirror_matrix_|thum)(?:four_home|two_bottom|two_num|five_bottom|five_num)/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, 2.0]
          rotate: 90
      # Move a diode so it doesn't conflict with the controller
      diode_nano_conflict:
        what: diode
        where: mirror_matrix_six_num
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, -1.0]
          rotate: 90
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_six_num
          shift: [-9, -1.5]
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_four_home
          shift: [-4, 6.0]
          rotate: 90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch (horizontal community version)
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_six_top
          shift: [9.0, 2.8]
          rotate: -90.0
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_six_top
          shift: [8.8, -12.0]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_matrix_five_mod
          shift: [-px, py]
      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_matrix_one_bottom
          shift: [px, -py]
      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_matrix_two_num
          shift: [-px, -py]
      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_matrix_five_top
          shift: [-px, py]
      hole_center:
        what: mountinghole
        where:
          ref: mirror_matrix_three_bottom
          shift: [px, py]
      front_text: &text
        what: text
        where: &textWhere
          ref: mirror_matrix_four_num
          shift: [8.7, 5.5]
        params: &textParams
          text: "[neolexis]"
          justify: left
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
cases:
  plate:
    - name: xl_board_key_cutouts
      extrude: 1.2
